
version: 2

models:
  - name: cars
    description: "This table contains details about cars."
    columns:
      - name: car_id
        description: "Unique identifier"
        tests:
          - unique
          - not_null
      - name: model
        description: "Model of the car."
        tests:
          - not_null
      - name: release_date
        description: "Date the car was made."
        tests:
          - not_null
      - name: price
        description: "Price of the car."
        tests:
          - not_null
      - name: car_rating
        description: "Experts' rating of the car."
        tests:
          - not_null
      

  - name: manufacturers
    description: "This table contains details about manufacturers."
    columns:
      - name: manufacturer_id
        description: "Unique identifier of the manufacturer."
        tests:
          - unique
          - not_null
      - name: manufacturer_name
        description: "Name of the manufacturer."
        tests:


  - name: manufacturers_cars
    description: "This table maps cars to their manufacturers."
    columns:
      - name: manufacturer_id
        description: "Identifier of the manufacturer."
        tests:
          - not_null
      - name: car_id
        description: "Identifier of the car."
        tests:
          - not_null
  

  - name: car_prices
    description: "This model aggregates car data and calculates the average price for each manufacturer."
    columns:
      - name: m_id
        description: "The unique identifier of each manufacturer."
        tests:
          - unique
          - not_null

      - name: m_name
        description: "The name of the manufacturer."
        tests:
          - not_null

      - name: avg_price
        description: "Average price of a car with this manufacturer."
        tests:
          - not_null